%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

%% document settings
\documentclass[10pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{euler}
\usepackage{xunicode,xltxtra}
\usepackage{fontspec}

\usepackage[a4paper, margin = 1 in, left = .5 in, right = .5 in]{geometry}

\usepackage{setspace}
\usepackage[dvipsnames]{xcolor}

% fonts
	\defaultfontfeatures{Mapping=tex-text, Ligatures=TeX}
	\setromanfont[Mapping=tex-text, Numbers={Proportional}]{Linux Biolinum}
	\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Optima}
	\setmonofont[Scale=MatchLowercase]{Andale Mono}

\usepackage{amsmath}
\usepackage{amssymb}
% \usepackage{mathtools}
\usepackage{linguex}
\usepackage{booktabs}

\usepackage[colorlinks=true,citecolor=MidnightBlue,urlcolor=MidnightBlue,linkcolor=MidnightBlue]{hyperref}

\title{Effects on projectivity ratings by Embedding Operator and Trigger --- \newline Data Analysis}
\author{Lisa Hofmann}
\date{\today}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\setkeys{Gin}{width=1.0\textwidth}


\maketitle
\setcounter{tocdepth}{2}
\tableofcontents

\section{Introducing the dataset}




\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{str}\hlstd{(data_all)}
\end{alltt}
\begin{verbatim}
'data.frame':	57160 obs. of  9 variables:
 $ workerid     : Factor w/ 2682 levels "1","3","4","5",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ content      : Factor w/ 20 levels "charley","danny",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ short_trigger: chr  "acknowledge" "hear" "reveal" "discover" ...
 $ ai_block     : chr  "block1" "block1" "block1" "block1" ...
 $ ai           : num  0.98 0.99 0.99 0.99 0.98 0.98 1 0.99 0.99 0.99 ...
 $ projective   : num  0.3 0.98 0.01 0.99 0.98 0.99 0.01 0.01 0.27 0.01 ...
 $ verb         : Factor w/ 20 levels "acknowledge",..: 1 11 16 9 18 13 17 7 14 8 ...
 $ op           : Factor w/ 4 levels "q","n","m","c": 1 1 1 1 1 1 1 1 1 1 ...
 $ exp_block    : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{workerid))}
\end{alltt}
\begin{verbatim}
[1] 2682
\end{verbatim}
\end{kframe}
\end{knitrout}


\noindent The dataset consists of $57160$ observations from $2682$ participants (recruited on the online platforms Prolific and Amazon Mechanical Turk), across 12 experiments.

We are interested in how highly participants rate speaker commitment to the truth of an embedded complement clause, coded as \texttt{projective} on a real-numbered sliding scale between $0-1$.\\

\noindent The complement clause was embedded under an attitude verb, which in turn was embedded under an entailment-cancelling operator. Our fixed effects factors manipulate the following:

\begin{enumerate}
  \item The choice of attitude verb (coded as \texttt{verb})
  \item The entailment-cancelling operator (coded as \texttt{op})
\end{enumerate}

\noindent The levels for our fixed effects factors are the following:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{verb)}
\end{alltt}
\begin{verbatim}
 [1] "acknowledge" "admit"       "announce"    "be_annoyed"  "be_right"   
 [6] "confess"     "confirm"     "demonstrate" "discover"    "establish"  
[11] "hear"        "inform"      "know"        "pretend"     "prove"      
[16] "reveal"      "say"         "see"         "suggest"     "think"      
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{verb))}
\end{alltt}
\begin{verbatim}
[1] 20
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{op)}
\end{alltt}
\begin{verbatim}
[1] "q" "n" "m" "c"
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 4
\end{verbatim}
\end{kframe}
\end{knitrout}

\noindent We are interested in the effect on \texttt{projective} of \texttt{verb} and \texttt{op}, as well as their interaction, corresponding to a $20 \times 4$ factorial design, yielding
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{verb))}\hlopt{*}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 80
\end{verbatim}
\end{kframe}
\end{knitrout}
conditions.\\

\noindent We have $20$ items, corresponding to the content of the complement clause.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{content)}
\end{alltt}
\begin{verbatim}
 [1] "charley"  "danny"    "emily"    "emma"     "frank"    "grace"   
 [7] "isabella" "jackson"  "jayden"   "jon"      "josh"     "josie"   
[13] "julian"   "mary"     "mia"      "olivia"   "owen"     "sophia"  
[19] "tony"     "zoe"     
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{content))}
\end{alltt}
\begin{verbatim}
[1] 20
\end{verbatim}
\end{kframe}
\end{knitrout}

\noindent We have roughly $36$ observations by item and condition. This is an approximate number, because the \texttt{op} manipulation is a between-studies manipulation, and the number of participants differs by experiment:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlcom{# n observations}
\hlstd{> }\hlkwd{length}\hlstd{(data_all[,}\hlnum{1}\hlstd{])}
\end{alltt}
\begin{verbatim}
[1] 57160
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by item}
\hlstd{> }\hlkwd{length}\hlstd{(data_all[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{content))}
\end{alltt}
\begin{verbatim}
[1] 2858
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(data_all}\hlopt{$}\hlstd{content)}
\end{alltt}
\begin{verbatim}

 charley    danny    emily     emma    frank    grace isabella  jackson 
    2858     2858     2858     2858     2858     2858     2858     2858 
  jayden      jon     josh    josie   julian     mary      mia   olivia 
    2858     2858     2858     2858     2858     2858     2858     2858 
    owen   sophia     tony      zoe 
    2858     2858     2858     2858 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by verb}
\hlstd{> }\hlkwd{length}\hlstd{(data_all[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{verb))}
\end{alltt}
\begin{verbatim}
[1] 2858
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(data_all}\hlopt{$}\hlstd{verb)}
\end{alltt}
\begin{verbatim}

acknowledge       admit    announce  be_annoyed    be_right     confess 
       2858        2858        2858        2858        2858        2858 
    confirm demonstrate    discover   establish        hear      inform 
       2858        2858        2858        2858        2858        2858 
       know     pretend       prove      reveal         say         see 
       2858        2858        2858        2858        2858        2858 
    suggest       think 
       2858        2858 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by operator}
\hlstd{> }\hlkwd{length}\hlstd{(data_all[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 14290
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(data_all}\hlopt{$}\hlstd{op)}
\end{alltt}
\begin{verbatim}

    q     n     m     c 
13740 14340 14680 14400 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by item and condition}
\hlstd{> }\hlkwd{length}\hlstd{(data_all[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{content))}\hlopt{/}
\hlstd{+ }  \hlstd{(}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{verb))}\hlopt{*}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(data_all}\hlopt{$}\hlstd{op)))}
\end{alltt}
\begin{verbatim}
[1] 35.725
\end{verbatim}
\end{kframe}
\end{knitrout}

\newpage
\section{Data Overview and Statistical Summaries}
\subsection{Distribution of projectivity ratings by operator:}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/figuresproject-by-op-distr-1} 

}


\end{knitrout}

\begin{itemize}
  \item These definitely do not look normal
  \item Maybe a beta-regression would be useful?
  \item But even that would be relying on some simplifying assumptions, since we might be ignoring the little bump in the middle 
\end{itemize}

\newpage
\subsection{Distribution of projectivity ratings by verb:}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/figuresproject-by-v-distr-1} 

}


\end{knitrout}

\begin{itemize}
  \item Some of these also show a higher mass around the middle of the scale
  \item but it looks the beta-distribution could be a useful approximation
\end{itemize}


\newpage
\subsection{Means and confidence intervals for projectivity rating by operator}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=.6\textwidth]{figures/figuressummary-op-1} 

}


\end{knitrout}
\noindent The following generalizations emerge:
\begin{itemize}
  \item Conditionals have the highest projectivity ratings
  \item Projectivity ratings for questions are higher than those for modals and negation, but lower than those for conditionals
  \item Modals and negation have the lowest projectivity ratings
  \item The ratings for negation look a little higher than for modals, but error bars overlap
\end{itemize}

\noindent Although these differences appear to be significant, they are quite small.\\

\newpage
\subsection{Means and confidence intervals for projectivity rating by verb:}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/figuressummary-v-1} 

}


\end{knitrout}
\begin{itemize}
  \item We see gradual differences in projectivity between verbs
\end{itemize}

\subsection{Means and confidence intervals for projectivity rating by verb and operator:}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/figuressummary-combined-1} 

}


\end{knitrout}

\begin{itemize}
  \item We see interactions between verb and operator
  \item However, we do not see any group of verbs that could be characterized as \lq semi-factive\rq\ in the sense of Karttunen. Specifically, \emph{discover} does not follow the predicted pattern: It is not more projective under negation, but most projective in conditionals and questions.
  
  \item Two verbs show highest projectivity under negation: the anti-veridical \emph{pretend}, and the non-veridical \emph{think}. These are verb with relatively low overall projectivity. 
  
  \item What else\dots?
\end{itemize}


\section{Analysis}

We are interested in how the response (projectivity ratings) depends on the verb and embedding operator.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlstd{formula} \hlkwb{<-} \hlstd{response} \hlopt{~} \hlstd{op} \hlopt{*} \hlstd{verb} \hlopt{+} \hlstd{(}\hlnum{1} \hlopt{|} \hlstd{workerid)} \hlopt{+} \hlstd{(}\hlnum{1} \hlopt{|} \hlstd{item)}
\hlstd{> }\hlcom{# formula <- response ~ op * verb + (1 + op + verb | workerid) + (1 + op + verb | item)}
\end{alltt}
\end{kframe}
\end{knitrout}

Trying a beta-regression. Our response variable has observations from a sliding scale between $(0,1)$. For beta regression, we rescale it to $[0,1]$, using method used in Degen \& Tonhauser (2022), from Smithson \& Verkuilen (2006).

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlstd{data_all}\hlopt{$}\hlstd{response} \hlkwb{=} \hlstd{(data_all}\hlopt{$}\hlstd{projective}\hlopt{*}\hlstd{(}\hlkwd{nrow}\hlstd{(data_all)}\hlopt{-}\hlnum{1}\hlstd{)} \hlopt{+} \hlnum{.5}\hlstd{)}\hlopt{/}\hlkwd{nrow}\hlstd{(data_all)}
\end{alltt}
\end{kframe}
\end{knitrout}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{library}\hlstd{(brms)}
\end{alltt}


{\ttfamily\noindent\itshape\color{messagecolor}{Loading required package: Rcpp}}

{\ttfamily\noindent\itshape\color{messagecolor}{Loading 'brms' package (version 2.16.3). Useful instructions\\can be found by typing help('brms'). A more detailed introduction\\to the package is available through vignette('brms\_overview').}}

{\ttfamily\noindent\itshape\color{messagecolor}{\\Attaching package: 'brms'}}

{\ttfamily\noindent\itshape\color{messagecolor}{The following object is masked from 'package:stats':

 \ \ \ ar}}\begin{alltt}
\hlstd{> }\hlstd{model1} \hlkwb{<-} \hlkwd{brm}\hlstd{(}\hlkwc{formula} \hlstd{= response} \hlopt{~} \hlstd{op} \hlopt{*} \hlstd{verb} \hlopt{+} \hlstd{(}\hlnum{1} \hlopt{|} \hlstd{workerid)} \hlopt{+} \hlstd{(}\hlnum{1} \hlopt{|} \hlstd{item),} \hlkwc{family} \hlstd{= )}
\end{alltt}


{\ttfamily\noindent\bfseries\color{errorcolor}{Error: Data must be specified using the 'data' argument.}}\end{kframe}
\end{knitrout}



\end{document}


