%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

%% document settings
\documentclass[10pt]{article}\usepackage[]{graphicx}\usepackage[dvipsnames]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{euler}
\usepackage{xunicode,xltxtra}
\usepackage{fontspec}

% fonts
	\defaultfontfeatures{Mapping=tex-text, Ligatures=TeX}
	\setromanfont[Mapping=tex-text, Numbers={Proportional}]{Linux Biolinum}
	\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Optima}
	\setmonofont[Scale=MatchLowercase]{Andale Mono}


\usepackage[a4paper, margin = 1 in, left = .5 in, right = .5 in]{geometry}

\usepackage{setspace}
\usepackage[dvipsnames]{xcolor}

\usepackage{amsmath}
\usepackage{amssymb}
% \usepackage{mathtools}
\usepackage{linguex}
\usepackage{booktabs}

\usepackage[colorlinks=true,citecolor=MidnightBlue,urlcolor=MidnightBlue,linkcolor=MidnightBlue]{hyperref}


\title{Effects on projectivity ratings by Embedding Operator and Trigger --- \newline Data Analysis}
\author{Hofmann, deMarneffe, Tonhauser}
\date{\today}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\setkeys{Gin}{width=1.0\textwidth}



\maketitle
\setcounter{tocdepth}{2}
\tableofcontents


\section{Introducing the dataset}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{str}\hlstd{(df)}
\end{alltt}
\begin{verbatim}
'data.frame':	57160 obs. of  9 variables:
 $ workerid     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ content      : chr  "charley" "danny" "emily" "emma" ...
 $ short_trigger: chr  "acknowledge" "hear" "reveal" "discover" ...
 $ ai_block     : chr  "block1" "block1" "block1" "block1" ...
 $ ai           : num  0.98 0.99 0.99 0.99 0.98 0.98 1 0.99 0.99 0.99 ...
 $ projective   : num  0.3 0.98 0.01 0.99 0.98 0.99 0.01 0.01 0.27 0.01 ...
 $ verb         : chr  "acknowledge" "hear" "reveal" "discover" ...
 $ op           : chr  "q" "q" "q" "q" ...
 $ exp_block    : int  1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlstd{df}\hlopt{$}\hlstd{workerid} \hlkwb{<-} \hlkwd{as.factor}\hlstd{(df}\hlopt{$}\hlstd{workerid)}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{workerid))}
\end{alltt}
\begin{verbatim}
[1] 2682
\end{verbatim}
\end{kframe}
\end{knitrout}


\noindent The dataset consists of $57160$ observations from $2682$ participants (recruited on the online platforms Prolific and Amazon Mechanical Turk), across 12 experiments.

We are interested in how highly participants rate speaker commitment to the truth of an embedded complement clause, coded as \texttt{projective} on a real-numbered sliding scale between $0-1$.\\

\noindent The complement clause was embedded under an attitude verb, which in turn was embedded under an entailment-cancelling operator. Our fixed effects factors manipulate the following:

\begin{enumerate}
  \item The choice of attitude verb (coded as \texttt{verb})
  \item The entailment-cancelling operator (coded as \texttt{op})
\end{enumerate}


\noindent The levels for our fixed effects factors are the following:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlstd{df}\hlopt{$}\hlstd{verb} \hlkwb{<-} \hlkwd{as.factor}\hlstd{(df}\hlopt{$}\hlstd{verb)}
\hlstd{> }\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{verb)}
\end{alltt}
\begin{verbatim}
 [1] "acknowledge" "admit"       "announce"    "be_annoyed"  "be_right"   
 [6] "confess"     "confirm"     "demonstrate" "discover"    "establish"  
[11] "hear"        "inform"      "know"        "pretend"     "prove"      
[16] "reveal"      "say"         "see"         "suggest"     "think"      
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{verb))}
\end{alltt}
\begin{verbatim}
[1] 20
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlstd{df}\hlopt{$}\hlstd{op} \hlkwb{<-} \hlkwd{as.factor}\hlstd{(df}\hlopt{$}\hlstd{op)}
\hlstd{> }\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{op)}
\end{alltt}
\begin{verbatim}
[1] "c" "m" "n" "q"
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 4
\end{verbatim}
\end{kframe}
\end{knitrout}

\noindent We are interested in the effect on \texttt{projective} of \texttt{verb} and \texttt{op}, as well as their interaction, corresponding to a $20 \times 4$ factorial design, yielding
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{verb))}\hlopt{*}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 80
\end{verbatim}
\end{kframe}
\end{knitrout}
conditions.\\

\noindent We have $20$ items, corresponding to the content of the complement clause.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlstd{df}\hlopt{$}\hlstd{content} \hlkwb{<-} \hlkwd{as.factor}\hlstd{(df}\hlopt{$}\hlstd{content)}
\hlstd{> }\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{content)}
\end{alltt}
\begin{verbatim}
 [1] "charley"  "danny"    "emily"    "emma"     "frank"    "grace"   
 [7] "isabella" "jackson"  "jayden"   "jon"      "josh"     "josie"   
[13] "julian"   "mary"     "mia"      "olivia"   "owen"     "sophia"  
[19] "tony"     "zoe"     
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{content))}
\end{alltt}
\begin{verbatim}
[1] 20
\end{verbatim}
\end{kframe}
\end{knitrout}

\noindent We have roughly $36$ observations by item and condition. This is an approximate number, because the \texttt{op} manipulation is a between-studies manipulation, and the number of participants differs by experiment:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{> }\hlcom{# n observations}
\hlstd{> }\hlkwd{length}\hlstd{(df[,}\hlnum{1}\hlstd{])}
\end{alltt}
\begin{verbatim}
[1] 57160
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by item}
\hlstd{> }\hlkwd{length}\hlstd{(df[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{content))}
\end{alltt}
\begin{verbatim}
[1] 2858
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(df}\hlopt{$}\hlstd{content)}
\end{alltt}
\begin{verbatim}

 charley    danny    emily     emma    frank    grace isabella  jackson 
    2858     2858     2858     2858     2858     2858     2858     2858 
  jayden      jon     josh    josie   julian     mary      mia   olivia 
    2858     2858     2858     2858     2858     2858     2858     2858 
    owen   sophia     tony      zoe 
    2858     2858     2858     2858 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by verb}
\hlstd{> }\hlkwd{length}\hlstd{(df[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{verb))}
\end{alltt}
\begin{verbatim}
[1] 2858
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(df}\hlopt{$}\hlstd{verb)}
\end{alltt}
\begin{verbatim}

acknowledge       admit    announce  be_annoyed    be_right     confess 
       2858        2858        2858        2858        2858        2858 
    confirm demonstrate    discover   establish        hear      inform 
       2858        2858        2858        2858        2858        2858 
       know     pretend       prove      reveal         say         see 
       2858        2858        2858        2858        2858        2858 
    suggest       think 
       2858        2858 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by operator}
\hlstd{> }\hlkwd{length}\hlstd{(df[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{op))}
\end{alltt}
\begin{verbatim}
[1] 14290
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlkwd{table}\hlstd{(df}\hlopt{$}\hlstd{op)}
\end{alltt}
\begin{verbatim}

    c     m     n     q 
14400 14680 14340 13740 
\end{verbatim}
\begin{alltt}
\hlstd{> }\hlcom{# observations by item and condition}
\hlstd{> }\hlkwd{length}\hlstd{(df[,}\hlnum{1}\hlstd{])}\hlopt{/}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{content))}\hlopt{/}
\hlstd{+ }  \hlstd{(}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{verb))}\hlopt{*}\hlkwd{length}\hlstd{(}\hlkwd{levels}\hlstd{(df}\hlopt{$}\hlstd{op)))}
\end{alltt}
\begin{verbatim}
[1] 35.725
\end{verbatim}
\end{kframe}
\end{knitrout}

\newpage
\section{Statistical Summaries and Graphs}
\subsection{Projectivity rating by operator}

Distribution of projectivity ratings by operator with means and $95\%$ bootstrapped confidence intervals.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=.6\textwidth]{figures/summary-op-1} 

}


\end{knitrout}

\noindent The following generalizations emerge:
\begin{itemize}
  \item Conditionals have the highest projectivity ratings
  \item Projectivity ratings for questions are higher than those for modals and negation, but lower than those for conditionals
  \item Modals and negation have the lowest projectivity ratings
  \item The ratings for negation look a little higher than for modals, but error bars overlap
\end{itemize}

\noindent Although these differences appear to be significant, they are quite small.\\

\newpage
\subsection{Distributions of projectivity rating by verb with means and 95\% bootstrapped confidence interval:}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/summary-verb-1} 

}


\end{knitrout}

\begin{itemize}
  \item We see gradual differences in projectivity between verbs
\end{itemize}


\subsection{Means and confidence intervals for projectivity rating by verb and operator:}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{figures/summary-combined-1} 

}


\end{knitrout}

\end{document}
